# Parse FASTA Files from MC_fasta Directory

This notebook reads FASTA files from the `B_metaclusters_xml/mc_info_from_xml/MC_fasta/` folder, extracts protein information, and creates a comprehensive DataFrame with columns: `mcid`, `protein`, `range`,`aa_length`, and `aa_seq`.

## Section 1: Import Required Libraries

In [1]:
# Necessary imports 
import pandas as pd
import os
from pathlib import Path
from typing import List, Tuple, Dict

## Section 2: Set Up File Path and Parameters

In [2]:
# Path to the FASTA folder
fasta_folder = Path('/u/mdmc/enyanduk/internship_areasciencepark/Data/dpcfam/dpcfam_b/zenodo_unzipped_folders/B_metaclusters_xml/mc_info_from_xml/MC_fasta/')

# Verify the folder exists
if fasta_folder.exists():
    print(f"Folder found at: {fasta_folder.absolute()}")
else:
    print(f"Folder not found at: {fasta_folder}")

# List all FASTA files in the folder
fasta_files = list(fasta_folder.glob('*.fasta'))
print(f"\nFound {len(fasta_files)} FASTA files")
if fasta_files:
    print("First few files:")
    for f in fasta_files[:5]:
        print(f"  - {f.name}")

Folder found at: /u/mdmc/enyanduk/internship_areasciencepark/Data/dpcfam/dpcfam_b/zenodo_unzipped_folders/B_metaclusters_xml/mc_info_from_xml/MC_fasta

Found 34556 FASTA files
First few files:
  - MC113651.fasta
  - MC195107.fasta
  - MC221075.fasta
  - MC53948.fasta
  - MC322411.fasta

## Section 3: Create Function to Parse FASTA Files

In [3]:
def parse_fasta_file(filepath: Path) -> List[Tuple[str, str, str]]:
    """
    Parse a FASTA file and extract protein, range, and amino acid sequence.
    
    Args:
        filepath: Path to the FASTA file
        
    Returns:
        List of tuples containing (protein_id, range, aa_sequence)
    """
    entries = []
    
    with open(filepath, 'r') as f:
        current_protein = None
        current_range = None
        current_sequence = []
        
        for line in f:
            line = line.strip()
            
            if line.startswith('>'):
                # Save the previous entry if it exists
                if current_protein is not None:
                    aa_sequence = ''.join(current_sequence)
                    entries.append((current_protein, current_range, aa_sequence))
                
                # Parse the header line
                # Format: >Protein/Range
                header = line[1:]  # Remove the '>'
                
                if '/' in header:
                    protein_id, range_str = header.split('/', 1)
                    current_protein = protein_id
                    current_range = range_str
                else:
                    # Handle case where there's no range
                    current_protein = header
                    current_range = ''
                
                current_sequence = []
            else:
                # This is a sequence line
                if line:  # Only add non-empty lines
                    current_sequence.append(line)
        
        # Don't forget to add the last entry
        if current_protein is not None:
            aa_sequence = ''.join(current_sequence)
            entries.append((current_protein, current_range, aa_sequence))
    
    return entries

In [4]:
# Test the function on a sample file
if fasta_files:
    sample_file = fasta_files[0]
    print(f"Testing parser on: {sample_file.name}")
    sample_entries = parse_fasta_file(sample_file)
    print(f"Found {len(sample_entries)} entries")
    if sample_entries:
        print(f"\nFirst entry example:")
        protein, range_val, aa = sample_entries[0]
        print(f"  Protein: {protein}")
        print(f"  Range: {range_val}")
        print(f"  AA (first 100 chars): {aa[:100]}...")
        print(f"  Total AA length: {len(aa)}")

Testing parser on: MC113651.fasta
Found 30 entries

First entry example:
  Protein: A0A0K6GCJ4
  Range: 2-376
  AA (first 100 chars): PTVVSSRALVPIGRRIRNAPEDSDASKAIVLRRKQQGETEDLSKALILRAPDDGRDDRQALVLYRRRGAQEMLRQLVAWHKSSALLPPFRMDELIRIADS...
  Total AA length: 375

## Section 4: Iterate Through FASTA Files in Directory

In [5]:
# Iterate through all FASTA files and collect data
all_data = []

print(f"Processing {len(fasta_files)} FASTA files...\n")

for idx, fasta_file in enumerate(fasta_files, 1):
    # Extract MCID from filename (e.g., MC1.fasta -> MC1)
    mcid = fasta_file.stem  # stem removes the .fasta extension
    
    # Parse the FASTA file
    try:
        entries = parse_fasta_file(fasta_file)
        
        # Add MCID to each entry
        for protein, range_val, aa_sequence in entries:
            all_data.append({
                'MCID': mcid,
                'Protein': protein,
                'Range': range_val,
                'AA': aa_sequence
            })
        
        print(f"[{idx}/{len(fasta_files)}] {fasta_file.name}: {len(entries)} entries processed")
    
    except Exception as e:
        print(f"[{idx}/{len(fasta_files)}] ✗ Error processing {fasta_file.name}: {str(e)}")

print(f"\nTotal entries collected: {len(all_data)}")

Processing 34556 FASTA files...

[1/34556] MC113651.fasta: 30 entries processed
[2/34556] MC195107.fasta: 32 entries processed
[3/34556] MC221075.fasta: 44 entries processed
[4/34556] MC53948.fasta: 45 entries processed
[5/34556] MC322411.fasta: 30 entries processed
[6/34556] MC69046.fasta: 34 entries processed
[7/34556] MC111882.fasta: 40 entries processed
[8/34556] MC142416.fasta: 31 entries processed
[9/34556] MC405129.fasta: 41 entries processed
[10/34556] MC298852.fasta: 36 entries processed
[11/34556] MC16441.fasta: 26 entries processed
[12/34556] MC475976.fasta: 43 entries processed
[13/34556] MC480307.fasta: 25 entries processed
[14/34556] MC118286.fasta: 34 entries processed
[15/34556] MC449689.fasta: 35 entries processed
[16/34556] MC224289.fasta: 28 entries processed
[17/34556] MC119536.fasta: 26 entries processed
[18/34556] MC34470.fasta: 31 entries processed
[19/34556] MC193492.fasta: 42 entries processed
[20/34556] MC91323.fasta: 43 entries processed
[21/34556] MC264220.fasta: 26 entries processed

[22/34556] MC59009.fasta: 29 entries processed
[23/34556] MC9618.fasta: 41 entries processed
[24/34556] MC248352.fasta: 41 entries processed
[25/34556] MC87614.fasta: 30 entries processed
[26/34556] MC38651.fasta: 45 entries processed
[27/34556] MC272419.fasta: 43 entries processed
[28/34556] MC51327.fasta: 39 entries processed
[29/34556] MC73756.fasta: 47 entries processed
[30/34556] MC376459.fasta: 37 entries processed
[31/34556] MC211706.fasta: 45 entries processed
[32/34556] MC30509.fasta: 37 entries processed
[33/34556] MC26088.fasta: 31 entries processed
[34/34556] MC116830.fasta: 44 entries processed
[35/34556] MC5509.fasta: 26 entries processed
[36/34556] MC156198.fasta: 38 entries processed
[37/34556] MC20073.fasta: 31 entries processed
[38/34556] MC46619.fasta: 47 entries processed
[39/34556] MC21755.fasta: 26 entries processed
[40/34556] MC6066.fasta: 29 entries processed
[41/34556] MC210038.fasta: 40 entries processed
[42/34556] MC126514.fasta: 29 entries processed
[43/34556] MC253587.fasta: 27 entries processed
[44/34556] MC42462.fasta: 37 entries processed
[45/34556] MC219611.fasta: 32 entries processed
[46/34556] MC99360.fasta: 32 entries processed
[47/34556] MC358165.fasta: 44 entries processed
[48/34556] MC267783.fasta: 25 entries processed
[49/34556] MC379343.fasta: 28 entries processed
[50/34556] MC8243.fasta: 31 entries processed
[51/34556] MC18706.fasta: 28 entries processed
[52/34556] MC478795.fasta: 27 entries processed
[53/34556] MC125019.fasta: 42 entries processed
[54/34556] MC272592.fasta: 25 entries processed
[55/34556] MC121542.fasta: 48 entries processed
[56/34556] MC319184.fasta: 40 entries processed
[57/34556] MC39387.fasta: 29 entries processed
[58/34556] MC59970.fasta: 43 entries processed
[59/34556] MC75147.fasta: 26 entries processed
[60/34556] MC182790.fasta: 44 entries processed
[61/34556] MC379101.fasta: 41 entries processed
[62/34556] MC305416.fasta: 45 entries processed
[63/34556] MC175271.fasta: 26 entries processed
[64/34556] MC37696.fasta: 25 entries processed
[65/34556] MC83236.fasta: 25 entries processed
[66/34556] MC29902.fasta: 31 entries processed
[67/34556] MC305549.fasta: 25 entries processed
[68/34556] MC104084.fasta: 47 entries processed
[69/34556] MC106940.fasta: 28 entries processed
[70/34556] MC97854.fasta: 25 entries processed
[71/34556] MC112770.fasta: 26 entries processed
[72/34556] MC286778.fasta: 48 entries processed
[73/34556] MC501537.fasta: 49 entries processed
[74/34556] MC233785.fasta: 33 entries processed
[75/34556] MC377647.fasta: 26 entries processed
[76/34556] MC404396.fasta: 41 entries processed
[77/34556] MC406988.fasta: 29 entries processed
[78/34556] MC357403.fasta: 44 entries processed
[79/34556] MC438187.fasta: 30 entries processed
[80/34556] MC91753.fasta: 27 entries processed
[81/34556] MC172879.fasta: 44 entries processed
[82/34556] MC212542.fasta: 44 entries processed
[83/34556] MC212348.fasta: 42 entries processed
[84/34556] MC86975.fasta: 28 entries processed
[85/34556] MC136837.fasta: 34 entries processed
[86/34556] MC239491.fasta: 26 entries processed
[87/34556] MC164922.fasta: 26 entries processed
[88/34556] MC211175.fasta: 39 entries processed
[89/34556] MC79446.fasta: 47 entries processed
[90/34556] MC18784.fasta: 35 entries processed
[91/34556] MC438442.fasta: 29 entries processed
[92/34556] MC188721.fasta: 45 entries processed
[93/34556] MC310675.fasta: 30 entries processed
[94/34556] MC273486.fasta: 44 entries processed
[95/34556] MC44047.fasta: 47 entries processed
[96/34556] MC127904.fasta: 37 entries processed
[97/34556] MC294700.fasta: 44 entries processed
[98/34556] MC16165.fasta: 42 entries processed
[99/34556] MC331939.fasta: 28 entries processed
[100/34556] MC14978.fasta: 40 entries processed
[101/34556] MC37660.fasta: 34 entries processed
[102/34556] MC139724.fasta: 28 entries processed
[103/34556] MC3088.fasta: 47 entries processed
[104/34556] MC123470.fasta: 28 entries processed
[105/34556] MC184173.fasta: 26 entries processed
[106/34556] MC11284.fasta: 38 entries processed
[107/34556] MC345951.fasta: 46 entries processed
[108/34556] MC440.fasta: 43 entries processed
[109/34556] MC151862.fasta: 40 entries processed
[110/34556] MC119665.fasta: 28 entries processed
[111/34556] MC391610.fasta: 32 entries processed
[112/34556] MC238545.fasta: 27 entries processed
[113/34556] MC24875.fasta: 31 entries processed
[114/34556] MC194843.fasta: 31 entries processed
[115/34556] MC258521.fasta: 34 entries processed
[116/34556] MC17677.fasta: 35 entries processed
[117/34556] MC409093.fasta: 40 entries processed
[118/34556] MC359541.fasta: 25 entries processed
[119/34556] MC5803.fasta: 39 entries processed
[120/34556] MC46768.fasta: 32 entries processed
[121/34556] MC169433.fasta: 27 entries processed
[122/34556] MC235341.fasta: 27 entries processed
[123/34556] MC333.fasta: 30 entries processed
[124/34556] MC476416.fasta: 40 entries processed
[125/34556] MC173885.fasta: 36 entries processed
[126/34556] MC78057.fasta: 32 entries processed
[127/34556] MC131200.fasta: 33 entries processed
[128/34556] MC485650.fasta: 31 entries processed
[129/34556] MC20975.fasta: 32 entries processed
[130/34556] MC455254.fasta: 39 entries processed
[131/34556] MC58387.fasta: 44 entries processed
[132/34556] MC394190.fasta: 32 entries processed
[133/34556] MC294616.fasta: 25 entries processed
[134/34556] MC32564.fasta: 32 entries processed
[135/34556] MC42899.fasta: 45 entries processed
[136/34556] MC407249.fasta: 48 entries processed
[137/34556] MC337269.fasta: 32 entries processed
[138/34556] MC23526.fasta: 48 entries processed
[139/34556] MC367725.fasta: 27 entries processed
[140/34556] MC180924.fasta: 34 entries processed
[141/34556] MC192264.fasta: 30 entries processed
[142/34556] MC41743.fasta: 32 entries processed
[143/34556] MC249844.fasta: 29 entries processed
[144/34556] MC185609.fasta: 47 entries processed
[145/34556] MC425199.fasta: 42 entries processed
[146/34556] MC69880.fasta: 34 entries processed
[147/34556] MC435998.fasta: 43 entries processed
[148/34556] MC290761.fasta: 37 entries processed
[149/34556] MC97970.fasta: 25 entries processed
[150/34556] MC150842.fasta: 46 entries processed
[151/34556] MC360867.fasta: 48 entries processed
[152/34556] MC72816.fasta: 31 entries processed
[153/34556] MC84653.fasta: 41 entries processed
[154/34556] MC328930.fasta: 27 entries processed
[155/34556] MC154045.fasta: 29 entries processed
[156/34556] MC39326.fasta: 36 entries processed
[157/34556] MC83285.fasta: 32 entries processed
[158/34556] MC70544.fasta: 44 entries processed
[159/34556] MC159970.fasta: 33 entries processed
[160/34556] MC74210.fasta: 30 entries processed
[161/34556] MC431889.fasta: 29 entries processed
[162/34556] MC11816.fasta: 46 entries processed
[163/34556] MC101552.fasta: 42 entries processed
[164/34556] MC450303.fasta: 35 entries processed
[165/34556] MC212493.fasta: 41 entries processed
[166/34556] MC102138.fasta: 48 entries processed
[167/34556] MC395769.fasta: 40 entries processed
[168/34556] MC65527.fasta: 37 entries processed
[169/34556] MC381656.fasta: 39 entries processed
[170/34556] MC41125.fasta: 32 entries processed
[171/34556] MC40331.fasta: 25 entries processed
[172/34556] MC139539.fasta: 28 entries processed
[173/34556] MC314625.fasta: 38 entries processed
[174/34556] MC31861.fasta: 36 entries processed
[175/34556] MC113903.fasta: 28 entries processed
[176/34556] MC155164.fasta: 45 entries processed
[177/34556] MC71943.fasta: 37 entries processed
[178/34556] MC278577.fasta: 32 entries processed
[179/34556] MC411550.fasta: 25 entries processed
[180/34556] MC362548.fasta: 41 entries processed
[181/34556] MC236503.fasta: 46 entries processed
[182/34556] MC89374.fasta: 28 entries processed
[183/34556] MC207029.fasta: 36 entries processed
[184/34556] MC8553.fasta: 31 entries processed
[185/34556] MC283623.fasta: 42 entries processed
[186/34556] MC200893.fasta: 43 entries processed
[187/34556] MC367579.fasta: 32 entries processed
[188/34556] MC11073.fasta: 28 entries processed
[189/34556] MC188159.fasta: 35 entries processed
[190/34556] MC117010.fasta: 27 entries processed
[191/34556] MC387813.fasta: 45 entries processed
[192/34556] MC432607.fasta: 38 entries processed
[193/34556] MC331352.fasta: 30 entries processed
[194/34556] MC91595.fasta: 26 entries processed
[195/34556] MC169823.fasta: 36 entries processed
[196/34556] MC246031.fasta: 29 entries processed
[197/34556] MC372639.fasta: 37 entries processed
[198/34556] MC26520.fasta: 41 entries processed
[199/34556] MC437785.fasta: 30 entries processed
[200/34556] MC195560.fasta: 31 entries processed
[201/34556] MC208049.fasta: 41 entries processed
[202/34556] MC28081.fasta: 33 entries processed
[203/34556] MC443623.fasta: 30 entries processed
[204/34556] MC227377.fasta: 25 entries processed
[205/34556] MC250814.fasta: 29 entries processed
[206/34556] MC467857.fasta: 26 entries processed
[207/34556] MC347575.fasta: 42 entries processed
[208/34556] MC151114.fasta: 26 entries processed
[209/34556] MC53992.fasta: 49 entries processed
[210/34556] MC138741.fasta: 31 entries processed
[211/34556] MC119054.fasta: 28 entries processed
[212/34556] MC297513.fasta: 38 entries processed
[213/34556] MC54075.fasta: 26 entries processed
[214/34556] MC368411.fasta: 48 entries processed
[215/34556] MC200156.fasta: 32 entries processed
[216/34556] MC40922.fasta: 46 entries processed
[217/34556] MC88081.fasta: 29 entries processed
[218/34556] MC153407.fasta: 44 entries processed
[219/34556] MC39287.fasta: 38 entries processed
[220/34556] MC83637.fasta: 32 entries processed
[221/34556] MC480980.fasta: 28 entries processed
[222/34556] MC376940.fasta: 28 entries processed
[223/34556] MC474257.fasta: 28 entries processed
[224/34556] MC12623.fasta: 31 entries processed
[225/34556] MC129688.fasta: 32 entries processed
[226/34556] MC12655.fasta: 38 entries processed
[227/34556] MC198114.fasta: 35 entries processed
[228/34556] MC41336.fasta: 26 entries processed
[229/34556] MC118225.fasta: 31 entries processed
[230/34556] MC260276.fasta: 39 entries processed
[231/34556] MC318820.fasta: 47 entries processed
[232/34556] MC256277.fasta: 49 entries processed
[233/34556] MC291748.fasta: 47 entries processed
[234/34556] MC23638.fasta: 45 entries processed
[235/34556] MC83669.fasta: 34 entries processed
[236/34556] MC80134.fasta: 43 entries processed
[237/34556] MC153898.fasta: 36 entries processed
[238/34556] MC185115.fasta: 28 entries processed
[239/34556] MC16698.fasta: 40 entries processed
[240/34556] MC185300.fasta: 44 entries processed
[241/34556] MC97879.fasta: 25 entries processed
[242/34556] MC451749.fasta: 26 entries processed
[243/34556] MC190943.fasta: 26 entries processed
[244/34556] MC45691.fasta: 30 entries processed
[245/34556] MC92303.fasta: 28 entries processed
[246/34556] MC1861.fasta: 35 entries processed
[247/34556] MC111973.fasta: 27 entries processed
[248/34556] MC246387.fasta: 47 entries processed
[249/34556] MC351185.fasta: 33 entries processed
[250/34556] MC470247.fasta: 32 entries processed
[251/34556] MC10856.fasta: 34 entries processed
[252/34556] MC102809.fasta: 31 entries processed
[253/34556] MC418669.fasta: 36 entries processed
[254/34556] MC171100.fasta: 37 entries processed
[255/34556] MC25023.fasta: 48 entries processed
[256/34556] MC41396.fasta: 28 entries processed
[257/34556] MC28859.fasta: 25 entries processed
[258/34556] MC115731.fasta: 34 entries processed
[259/34556] MC281629.fasta: 32 entries processed
[260/34556] MC359189.fasta: 49 entries processed
[261/34556] MC56713.fasta: 45 entries processed
[262/34556] MC273306.fasta: 34 entries processed
[263/34556] MC485042.fasta: 34 entries processed
[264/34556] MC277194.fasta: 44 entries processed
[265/34556] MC280479.fasta: 40 entries processed
[266/34556] MC87140.fasta: 31 entries processed
[267/34556] MC22658.fasta: 25 entries processed
[268/34556] MC150384.fasta: 28 entries processed
[269/34556] MC467155.fasta: 35 entries processed
[270/34556] MC407162.fasta: 30 entries processed
[271/34556] MC82511.fasta: 45 entries processed
[272/34556] MC270377.fasta: 48 entries processed
[273/34556] MC410913.fasta: 29 entries processed
[274/34556] MC314336.fasta: 30 entries processed
[275/34556] MC64426.fasta: 45 entries processed
[276/34556] MC395084.fasta: 25 entries processed
[277/34556] MC26121.fasta: 25 entries processed
[278/34556] MC241427.fasta: 25 entries processed
[279/34556] MC337100.fasta: 46 entries processed
[280/34556] MC291472.fasta: 35 entries processed
[281/34556] MC132301.fasta: 36 entries processed
[282/34556] MC302032.fasta: 25 entries processed
[283/34556] MC119091.fasta: 48 entries processed
[284/34556] MC69405.fasta: 30 entries processed
[285/34556] MC390061.fasta: 30 entries processed
[286/34556] MC11868.fasta: 26 entries processed
[287/34556] MC89.fasta: 25 entries processed
[288/34556] MC325635.fasta: 42 entries processed
[289/34556] MC301265.fasta: 31 entries processed
[290/34556] MC232872.fasta: 27 entries processed
[291/34556] MC425341.fasta: 33 entries processed
[292/34556] MC19158.fasta: 28 entries processed
[293/34556] MC114158.fasta: 33 entries processed
[294/34556] MC190926.fasta: 30 entries processed
[295/34556] MC40100.fasta: 25 entries processed
[296/34556] MC385353.fasta: 37 entries processed
[297/34556] MC5030.fasta: 40 entries processed
[298/34556] MC77243.fasta: 49 entries processed
[299/34556] MC84531.fasta: 39 entries processed
[300/34556] MC106246.fasta: 42 entries processed
[301/34556] MC77550.fasta: 38 entries processed
[302/34556] MC20084.fasta: 32 entries processed
[303/34556] MC12855.fasta: 33 entries processed
[304/34556] MC4145.fasta: 43 entries processed
[305/34556] MC256169.fasta: 25 entries processed
[306/34556] MC89925.fasta: 45 entries processed
[307/34556] MC201626.fasta: 25 entries processed
[308/34556] MC162945.fasta: 25 entries processed
[309/34556] MC268379.fasta: 35 entries processed
[310/34556] MC496188.fasta: 34 entries processed
[311/34556] MC421723.fasta: 33 entries processed
[312/34556] MC470934.fasta: 25 entries processed
[313/34556] MC53145.fasta: 40 entries processed
[314/34556] MC7290.fasta: 33 entries processed
[315/34556] MC218751.fasta: 33 entries processed
[316/34556] MC425638.fasta: 46 entries processed
[317/34556] MC249202.fasta: 45 entries processed
[318/34556] MC378448.fasta: 29 entries processed
[319/34556] MC24739.fasta: 25 entries processed
[320/34556] MC6215.fasta: 41 entries processed
[321/34556] MC364267.fasta: 29 entries processed
[322/34556] MC65697.fasta: 28 entries processed
[323/34556] MC17562.fasta: 37 entries processed
[324/34556] MC272645.fasta: 45 entries processed
[325/34556] MC28198.fasta: 42 entries processed
[326/34556] MC91378.fasta: 47 entries processed
[327/34556] MC26304.fasta: 29 entries processed
[328/34556] MC61957.fasta: 30 entries processed
[329/34556] MC39633.fasta: 27 entries processed
[330/34556] MC149370.fasta: 38 entries processed
[331/34556] MC478792.fasta: 43 entries processed
[332/34556] MC414647.fasta: 29 entries processed
[333/34556] MC11326.fasta: 33 entries processed
[334/34556] MC500641.fasta: 25 entries processed
[335/34556] MC54292.fasta: 25 entries processed
[336/34556] MC262007.fasta: 26 entries processed
[337/34556] MC212484.fasta: 27 entries processed
[338/34556] MC340799.fasta: 30 entries processed
[339/34556] MC164663.fasta: 36 entries processed
[340/34556] MC293133.fasta: 40 entries processed
[341/34556] MC12384.fasta: 25 entries processed
[342/34556] MC466427.fasta: 48 entries processed
[343/34556] MC111277.fasta: 39 entries processed
[344/34556] MC46048.fasta: 27 entries processed
[345/34556] MC17599.fasta: 27 entries processed
[346/34556] MC109338.fasta: 37 entries processed
[347/34556] MC49526.fasta: 28 entries processed
[348/34556] MC206343.fasta: 35 entries processed
[349/34556] MC363815.fasta: 30 entries processed
[350/34556] MC212209.fasta: 44 entries processed
[351/34556] MC274329.fasta: 46 entries processed
[352/34556] MC302470.fasta: 27 entries processed
[353/34556] MC689.fasta: 25 entries processed
[354/34556] MC172216.fasta: 27 entries processed
[355/34556] MC23046.fasta: 36 entries processed
[356/34556] MC162751.fasta: 35 entries processed
[357/34556] MC36495.fasta: 34 entries processed
[358/34556] MC3887.fasta: 37 entries processed
[359/34556] MC10516.fasta: 48 entries processed
[360/34556] MC143927.fasta: 33 entries processed
[361/34556] MC44959.fasta: 27 entries processed
[362/34556] MC50267.fasta: 34 entries processed
[363/34556] MC105519.fasta: 27 entries processed
[364/34556] MC112446.fasta: 28 entries processed
[365/34556] MC181837.fasta: 25 entries processed
[366/34556] MC231692.fasta: 39 entries processed
[367/34556] MC425286.fasta: 26 entries processed
[368/34556] MC165286.fasta: 33 entries processed
[369/34556] MC4976.fasta: 28 entries processed
[370/34556] MC235336.fasta: 32 entries processed
[371/34556] MC202063.fasta: 44 entries processed
[372/34556] MC397713.fasta: 25 entries processed
[373/34556] MC9079.fasta: 37 entries processed
[374/34556] MC376994.fasta: 25 entries processed
[375/34556] MC387175.fasta: 28 entries processed
[376/34556] MC30542.fasta: 27 entries processed
[377/34556] MC377532.fasta: 30 entries processed
[378/34556] MC8493.fasta: 25 entries processed
[379/34556] MC86742.fasta: 45 entries processed
[380/34556] MC122601.fasta: 35 entries processed
[381/34556] MC96290.fasta: 33 entries processed
[382/34556] MC3402.fasta: 33 entries processed
[383/34556] MC471422.fasta: 27 entries processed
[384/34556] MC64334.fasta: 41 entries processed
[385/34556] MC98846.fasta: 34 entries processed
[386/34556] MC34652.fasta: 41 entries processed
[387/34556] MC431684.fasta: 41 entries processed
[388/34556] MC26803.fasta: 31 entries processed
[389/34556] MC466605.fasta: 38 entries processed
[390/34556] MC286269.fasta: 25 entries processed
[391/34556] MC11662.fasta: 26 entries processed
[392/34556] MC5639.fasta: 49 entries processed
[393/34556] MC197754.fasta: 35 entries processed
[394/34556] MC113298.fasta: 30 entries processed
[395/34556] MC214567.fasta: 38 entries processed
[396/34556] MC208878.fasta: 42 entries processed
[397/34556] MC461842.fasta: 49 entries processed
[398/34556] MC124174.fasta: 27 entries processed
[399/34556] MC261612.fasta: 25 entries processed
[400/34556] MC100955.fasta: 42 entries processed
[401/34556] MC87826.fasta: 39 entries processed
[402/34556] MC396413.fasta: 27 entries processed
[403/34556] MC22693.fasta: 26 entries processed
[404/34556] MC371045.fasta: 37 entries processed
[405/34556] MC330543.fasta: 47 entries processed
[406/34556] MC65612.fasta: 33 entries processed
[407/34556] MC20815.fasta: 28 entries processed
[408/34556] MC246878.fasta: 34 entries processed
[409/34556] MC318943.fasta: 37 entries processed
[410/34556] MC59844.fasta: 32 entries processed
[411/34556] MC18759.fasta: 26 entries processed
[412/34556] MC318980.fasta: 29 entries processed
[413/34556] MC119987.fasta: 38 entries processed
[414/34556] MC111599.fasta: 28 entries processed
[415/34556] MC234289.fasta: 34 entries processed
[416/34556] MC241769.fasta: 42 entries processed
[417/34556] MC134977.fasta: 31 entries processed
[418/34556] MC489113.fasta: 48 entries processed
[419/34556] MC5848.fasta: 25 entries processed
[420/34556] MC495668.fasta: 46 entries processed
[421/34556] MC226004.fasta: 27 entries processed
[422/34556] MC21301.fasta: 46 entries processed
[423/34556] MC12435.fasta: 31 entries processed
[424/34556] MC263478.fasta: 30 entries processed
[425/34556] MC179647.fasta: 25 entries processed
[426/34556] MC186504.fasta: 29 entries processed
[427/34556] MC380624.fasta: 38 entries processed
[428/34556] MC337001.fasta: 38 entries processed
[429/34556] MC353547.fasta: 49 entries processed
[430/34556] MC107222.fasta: 38 entries processed
[431/34556] MC462368.fasta: 44 entries processed
[432/34556] MC76618.fasta: 30 entries processed
[433/34556] MC107205.fasta: 49 entries processed
[434/34556] MC24541.fasta: 43 entries processed

## Section 5: Process and Extract Data

In [6]:
# Add calculated column for sequence length
for entry in all_data:
    entry['Sequence_Length'] = len(entry['AA'])

# Display data statistics
print(f"Total entries: {len(all_data)}")
print(f"Number of unique MCIDs: {len(set(entry['MCID'] for entry in all_data))}")
print(f"Number of unique Proteins: {len(set(entry['Protein'] for entry in all_data))}")
print(f"\nSequence length statistics:")
sequence_lengths = [entry['Sequence_Length'] for entry in all_data]
print(f"  Min: {min(sequence_lengths)}")
print(f"  Max: {max(sequence_lengths)}")
print(f"  Average: {sum(sequence_lengths)/len(sequence_lengths):.2f}")

# Show sample entries
print(f"\nFirst 3 entries:")
for i, entry in enumerate(all_data[:3], 1):
    print(f"  {i}. MCID={entry['MCID']}, Protein={entry['Protein']}, Range={entry['Range']}, "
          f"AA_length={entry['Sequence_Length']}")

Total entries: 1200826
Number of unique MCIDs: 34556
Number of unique Proteins: 1014273

Sequence length statistics:
  Min: 27
  Max: 3545
  Average: 181.18

First 3 entries:
  1. MCID=MC113651, Protein=A0A0K6GCJ4, Range=2-376, AA_length=375
  2. MCID=MC113651, Protein=A8N621, Range=40-384, AA_length=345
  3. MCID=MC113651, Protein=A0A0H2RRJ7, Range=98-399, AA_length=302

## Section 6: Create DataFrame from Extracted Data

In [ ]:
# Create DataFrame with the four required columns
df = pd.DataFrame(all_data)

# Select and reorder columns to match requirements
df = df[['MCID', 'Protein', 'Range', 'AA']]
# We so

print("DataFrame created successfully!")
print(f"Shape: {df.shape}")
print(f"\nColumn dtypes:")
print(df.dtypes)
print(f"\nDataFrame info:")
print(df.info())

DataFrame created successfully!
Shape: (1200826, 4)

Column dtypes:
MCID       object
Protein    object
Range      object
AA         object
dtype: object

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200826 entries, 0 to 1200825
Data columns (total 4 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   MCID     1200826 non-null  object
 1   Protein  1200826 non-null  object
 2   Range    1200826 non-null  object
 3   AA       1200826 non-null  object
dtypes: object(4)
memory usage: 36.6+ MB
None

## Section 7: Display and Save Results

In [8]:
# Add a column for sequence length
df['AALength'] = df['AA'].apply(len)
# Rearrange  columns to put AA at the end
df = df[['MCID', 'Protein', 'Range', 'AALength', 'AA']]

In [9]:
# Display the head of the DataFrame
print("\nDataFrame head:")
df.head()

DataFrame head:

,MCID,Protein,Range,AALength,AA
0,MC113651,A0A0K6GCJ4,2-376,375,PTVVSSRALVPIGRRIRNAPEDSDASKAIVLRRKQQGETEDLSKAL...
1,MC113651,A8N621,40-384,345,TRALILRNGKHGAMGTGEIIASNKITGREKLDLLAEELIEKMKTAV...
2,MC113651,A0A0H2RRJ7,98-399,302,SNAVRAPFDLDSLIRWSQSQMDAALDQVNNLHETDFCYEIVERHIS...
3,MC113651,G4TJX7,26-369,344,VILSNQRREFVNTSSNAIALRYEPHGIWGEGQLASFKKRSGQEKLA...
4,MC113651,UPI0004449C2E,4-413,410,PPKDSKQPKDAPASTSRDLVRVGPRHVSAKHVVGRRNEDGQKPTTA...

In [10]:
# Summary statistics
print("\nSummary statistics:")
df.describe().T

Summary statistics:

              count        mean         std   min   25%    50%    75%     max
AALength  1200826.0  181.176998  181.632418  27.0  78.0  121.0  212.0  3545.0

In [11]:
# More derailed summary statistics
print("\n" + "="*80)
print("SUMMARY STATISTICS")
print("="*80)
print(f"Total rows: {len(df)}")
print(f"Total columns: {len(df.columns)}")
print(f"\nMCIDs represented: {df['MCID'].nunique()}")
print(f"Unique Proteins: {df['Protein'].nunique()}")

print(f"\nMCID distribution:")
print(df['MCID'].value_counts().head(10))

# Check for any missing values
print(f"\nMissing values:")
print(df.isnull().sum())

# Amino acid sequence length statistics
print(f"\nAmino acid sequence length statistics:")
df['AA_Length'] = df['AA'].str.len()
print(f"  Min length: {df['AA_Length'].min()}")
print(f"  Max length: {df['AA_Length'].max()}")
print(f"  Mean length: {df['AA_Length'].mean():.2f}")
print(f"  Median length: {df['AA_Length'].median():.2f}")

================================================================================
SUMMARY STATISTICS
================================================================================
Total rows: 1200826
Total columns: 5

MCIDs represented: 34556

Unique Proteins: 1014273

MCID distribution:
MCID
MC331055    49
MC343031    49
MC103575    49
MC30001     49
MC304682    49
MC88295     49
MC101962    49
MC14331     49
MC29941     49
MC102068    49
Name: count, dtype: int64

Missing values:
MCID        0
Protein     0
Range       0
AALength    0
AA          0
dtype: int64

Amino acid sequence length statistics:
  Min length: 27
  Max length: 3545
  Mean length: 181.18
  Median length: 121.00

In [12]:
# Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200826 entries, 0 to 1200825
Data columns (total 6 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   MCID       1200826 non-null  object
 1   Protein    1200826 non-null  object
 2   Range      1200826 non-null  object
 3   AALength   1200826 non-null  int64
 4   AA         1200826 non-null  object
 5   AA_Length  1200826 non-null  int64
dtypes: int64(2), object(4)
memory usage: 55.0+ MB

In [13]:
# Let's organise columns properly for PostgreSQL needs :
# 1. We drop AA_Length:
df = df.drop(columns=["AA_Length"])
# 2. We renamme columns properly:
df = df.rename(columns={
    "MCID":"mcid",
    "Protein":"protein_id",
    "Range":"seq_range",
    "AALength":"seq_length",
    "AA" : "aa_seq"
    })
df.head()

,mcid,protein_id,seq_range,seq_length,aa_seq
0,MC113651,A0A0K6GCJ4,2-376,375,PTVVSSRALVPIGRRIRNAPEDSDASKAIVLRRKQQGETEDLSKAL...
1,MC113651,A8N621,40-384,345,TRALILRNGKHGAMGTGEIIASNKITGREKLDLLAEELIEKMKTAV...
2,MC113651,A0A0H2RRJ7,98-399,302,SNAVRAPFDLDSLIRWSQSQMDAALDQVNNLHETDFCYEIVERHIS...
3,MC113651,G4TJX7,26-369,344,VILSNQRREFVNTSSNAIALRYEPHGIWGEGQLASFKKRSGQEKLA...
4,MC113651,UPI0004449C2E,4-413,410,PPKDSKQPKDAPASTSRDLVRVGPRHVSAKHVVGRRNEDGQKPTTA...

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200826 entries, 0 to 1200825
Data columns (total 5 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   mcid        1200826 non-null  object
 1   protein_id  1200826 non-null  object
 2   seq_range   1200826 non-null  object
 3   seq_length  1200826 non-null  int64
 4   aa_seq      1200826 non-null  object
dtypes: int64(1), object(4)
memory usage: 45.8+ MB

In [15]:
# Save the DataFrame to CSV file
output_path = Path('/u/mdmc/enyanduk/internship_areasciencepark/Dataframes/DPCFam/DPCFamB/dpcfamB_sequences.csv')
output_path.parent.mkdir(parents=True, exist_ok=True)

df.to_csv(output_path, index=False)
print(f"\nDataFrame saved to: {output_path.absolute()}")
print(f"File size: {output_path.stat().st_size / 1024 / 1024:.2f} MB")

print("\n" + "="*80)
print("PROCESSING COMPLETE!")
print("="*80)

DataFrame saved to: /u/mdmc/enyanduk/internship_areasciencepark/Dataframes/DPCFam/DPCFamB/dpcfamB_sequences.csv
File size: 242.41 MB

================================================================================
PROCESSING COMPLETE!
================================================================================