In [1]:
# Imports
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# I. Dataset Source : UniRef50

In [2]:
df = pd.read_csv("/u/mdmc/enyanduk/internship_areasciencepark/Dataframes/DPCFam/uniref50_proteins.csv")
df.head()

  uniref50_id  uniprotkb_id uniprotkb_accession  length
0    Q8WZ42-5      Q8WZ42-5            Q8WZ42-5   32900
1      Q3ASY8  Q3ASY8_CHLCH              Q3ASY8   36805
2      G5B0U1  G5B0U1_HETGA              G5B0U1   36507
3      Q8WZ42   TITIN_HUMAN              Q9Y6L9   34350
4      K7EE71  K7EE71_ORNAN              K7EE71    7472

In [3]:
# We need only two columns: "uniref50_id" and "length"
df = df[["uniref50_id", "length"]]
# We rename uniref50_id to protein_id and length to protein_length
df = df.rename(columns={"uniref50_id": "protein_id", "length": "protein_length"})
df.head()

  protein_id  protein_length
0   Q8WZ42-5           32900
1     Q3ASY8           36805
2     G5B0U1           36507
3     Q8WZ42           34350
4     K7EE71            7472

In [4]:
# How many unique protein_ids do we have in uniref50_proteins.csv?
uniref50_unique_protein_ids = df["protein_id"].nunique()
print("Number of unique protein_ids in uniref50_proteins.csv:", uniref50_unique_protein_ids)

Number of unique protein_ids in uniref50_proteins.csv: 23531980

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23531980 entries, 0 to 23531979
Data columns (total 2 columns):
 #   Column          Dtype
---  ------          -----
 0   protein_id      object
 1   protein_length  int64
dtypes: int64(1), object(1)
memory usage: 359.1+ MB

# II. Filtering UniRef50-PFam proteins in the source

In [6]:
df_pfam = pd.read_csv("/u/mdmc/enyanduk/internship_areasciencepark/Dataframes/DPCFam/uniref50_pfam_valid.csv")
df_pfam.head()

  uniref50_id pfam_ids  pfam_ranges
0      G5B0U1  PF07679  15159-15237
1      G5B0U1  PF07679  11109-11197
2      G5B0U1  PF07679  10241-10328
3      G5B0U1  PF07679    2348-2427
4      G5B0U1  PF07679  31048-31127

In [7]:
# How many unique protein_ids do we have in pfam_valid.csv?
pfam_unique_protein_ids = df_pfam["uniref50_id"].nunique()
print("Number of unique protein_ids in pfam_valid.csv:", pfam_unique_protein_ids)

Number of unique protein_ids in pfam_valid.csv: 9315206

In [8]:
# We  need a subdaframe of df corresponding to the unique protein_ids in pfam_valid.csv
df_pfam_unique_protein_ids = df_pfam["uniref50_id"].unique()
df_pfam_protein_lengths = df[df["protein_id"].isin(df_pfam_unique_protein_ids)]
df_pfam_protein_lengths.head()

  protein_id  protein_length
2     G5B0U1           36507
3     Q8WZ42           34350
4     K7EE71            7472
5     W5MH34           32359
6     G1P5X9           34984

In [9]:
# Info
df_pfam_protein_lengths.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9315206 entries, 2 to 23531976
Data columns (total 2 columns):
 #   Column          Dtype
---  ------          -----
 0   protein_id      object
 1   protein_length  int64
dtypes: int64(1), object(1)
memory usage: 213.2+ MB

# III. Filtering DPCFam proteins in the source

In [10]:
df_dpcfam = pd.read_csv("/u/mdmc/enyanduk/internship_areasciencepark/Dataframes/DPCFam/Merged/dpcfam_all_mcs_sequences.csv")
df_dpcfam.head()

,mcid,protein_id,seq_range,seq_length,aa_seq
0,MC1,B0C3J8,589-773,185,FRSLYSQLHLLNPDLPISSLVISSCSPQEGKSTTSMHLAQAAAAMG...
1,MC1,I4CCA7,496-701,206,LTNAFRNIQTSISFVVEDSDMKTWVLSSAIPQEGKSFVSMSLAFTY...
2,MC1,A0A0K2GDM9,61-257,197,YRTLGLMLEQRRQTGLLQVVAMTSPTMGDGKTLTAINLAGAVSQSP...
3,MC1,A0A1R3X2Q7,585-760,176,SIRINLQYLMSETDFKVVGVTSSVSGEGKTFTSVNLSSEMAMAGKR...
4,MC1,A0A084U454,6-185,180,IIGVVNNKGGVLKTTLSTNLGACLSLDSKKTIIVDLDGQGNVIATF...

In [11]:
# How many unique protein_ids do we have in dpcfam_all_mcs_sequences.csv?
dpcfam_unique_protein_ids = df_dpcfam["protein_id"].nunique()
print("Number of unique protein_ids in dpcfam_all_mcs_sequences.csv:", dpcfam_unique_protein_ids)

Number of unique protein_ids in dpcfam_all_mcs_sequences.csv: 10540602

In [12]:
# We  need a subdaframe of df corresponding to the unique protein_ids in dpcfam_all_mcs_sequences.csv
df_dpcfam_unique_protein_ids = df_dpcfam["protein_id"].unique()
df_dpcfam_protein_lengths = df[df["protein_id"].isin(df_dpcfam_unique_protein_ids)]
df_dpcfam_protein_lengths.head()

  protein_id  protein_length
0   Q8WZ42-5           32900
1     Q3ASY8           36805
2     G5B0U1           36507
3     Q8WZ42           34350
4     K7EE71            7472

In [13]:
# Info
df_dpcfam_protein_lengths.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10540602 entries, 0 to 23531979
Data columns (total 2 columns):
 #   Column          Dtype
---  ------          -----
 0   protein_id      object
 1   protein_length  int64
dtypes: int64(1), object(1)
memory usage: 241.3+ MB

# III. DPCStruct Proteins

In [14]:
df_dpcstruct = pd.read_csv("/u/mdmc/enyanduk/internship_areasciencepark/Dataframes/DPCStruct/dpcstruct_all_proteins_lengths.csv")
# We rename length to dpcstruct_length
df_dpcstruct = df_dpcstruct.rename(columns={"length": "protein_length"})
df_dpcstruct.head()

   protein_id  protein_length
0  A0A090M7B6             892
1      F1MAE5             895
2      B8JI51            1992
3      K1PN73              98
4      M1CI46             681

In [15]:
# Info
df_dpcstruct.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1252179 entries, 0 to 1252178
Data columns (total 2 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   protein_id      1252179 non-null  object
 1   protein_length  1252179 non-null  int64
dtypes: int64(1), object(1)
memory usage: 19.1+ MB

# IV. Putting everything (Pfam, DPCFam, DPCStruct) together

In [16]:
# Is there any intersection between dpcfam and dpcstruct protein_ids?
dpcstruct_protein_ids = set(df_dpcstruct["protein_id"])
dpcfam_protein_ids = set(df_dpcfam_protein_lengths["protein_id"])
intersection_protein_ids = dpcstruct_protein_ids.intersection(dpcfam_protein_ids)
print("Number of intersecting protein_ids between dpcfam and dpcstruct:", len(intersection_protein_ids))
# Print some of the intersecting protein_ids
print("Some intersecting protein_ids:", list(intersection_protein_ids)[:10])

Number of intersecting protein_ids between dpcfam and dpcstruct: 199496
Some intersecting protein_ids: ['A0A178UB89', 'Q4BUV0', 'G0QY88', 'A0A0R3WVA2', 'A0A139AN02', 'A0A1G2AQ47', 'A0A1E4TGK0', 'A0A135UP06', 'R5EFC1', 'A0A0B2V6P0']

In [17]:
# Intersection PFam, DPCFam and DPCStruct
pfam_protein_ids = set(df_pfam_protein_lengths["protein_id"])
intersection_all = pfam_protein_ids.intersection(dpcfam_protein_ids).intersection(dpcstruct_protein_ids)
print("Number of intersecting protein_ids between pfam, dpcfam and dpcstruct:", len(intersection_all))
# Print some of the intersecting protein_ids
print("Some intersecting protein_ids between pfam, dpcfam and dpcstruct:", list(intersection_all)[:10])

Number of intersecting protein_ids between pfam, dpcfam and dpcstruct: 144682
Some intersecting protein_ids between pfam, dpcfam and dpcstruct: ['A0A1J4W4F2', 'Q4BUV0', 'G0QY88', 'A0A160NUW5', 'A0A1I8FCP9', 'A0A183IMC6', 'A0A139AN02', 'I0Z589', 'A0A0L0VTR2', 'A0A1G2AQ47']

In [18]:
# We oncatenate the three dataframes
df = pd.concat([df_pfam_protein_lengths,df_dpcfam_protein_lengths, df_dpcstruct], ignore_index=True).drop_duplicates().reset_index(drop=True)
print(f"df shape: {df.shape}")
df.head()

df shape: (14112858, 2)

  protein_id  protein_length
0     G5B0U1           36507
1     Q8WZ42           34350
2     K7EE71            7472
3     W5MH34           32359
4     G1P5X9           34984

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14112858 entries, 0 to 14112857
Data columns (total 2 columns):
 #   Column          Dtype
---  ------          -----
 0   protein_id      object
 1   protein_length  int64
dtypes: int64(1), object(1)
memory usage: 215.3+ MB

In [20]:
# We save the dataframe as a csv file
df.to_csv("/u/mdmc/enyanduk/internship_areasciencepark/Dataframes/DPC/dpc_protein_lengths.csv", index=False)